app/models.py
from . import db
from datetime import datetime
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager

@login_manager.user_loader
def load_user(user_id):
    '''
    function that queries the database to check if user exists
    '''
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255), unique=True, index=True)
    date_joined = db.Column(db.DateTime,default=datetime.utcnow)
    pass_secure = db.Column(db.String(255))
    comment=db.relationship('Comment',backref='user',lazy='dynamic')
    parent=db.relationship('Parent', backref='Parent', lazy='dynamic')
    
    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')
    
    @password.setter
    def password(self,password):
        self.pass_secure = generate_password_hash(password)
        
    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User {self.username}'

class Admin(db.Model):
    __tablename__= 'admin'
    
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255))
    admin_title = db.Column(db.String(255))
    admin_content = db.Column(db.String(5000))
    
    def save_Admin(self):
        db.session.add(self)
        db.session.commit()
        
class Parent(db.Model):
    __tablename__='parent'
    
    id = db.Column(db.Integer,primary_key = True)
    title = db.Column(db.String(255))
    body = db.Column(db.String(5000))
    posted_on=db.Column(db.DateTime,default=datetime.utcnow)
    posted_by=db.Column(db.String(255))
    user_id=db.Column(db.Integer,db.ForeignKey('users.id'))
    
    
    def save_parent(self):
        db.session.add(self)
        db.session.commit()
        
    
class Comment(db.Model):
    __tablename__='comments'
    
    id = db.Column(db.Integer,primary_key=True)
    body = db.Column(db.String(255))
    posted_by=db.Column(db.String(255))
    posted_on=db.Column(db.DateTime,default=datetime.utcnow)
    user_id=db.Column(db.Integer,db.ForeignKey('users.id'))
    
    
    def save_comment(self):
        '''
        function that saves a new comment to the database
        '''
        db.session.add(self)
        db.session.commit()
        
    def get_comments():
        '''
        function that get comments for a parent 
        '''
        comments =  Comment.query.all()
        return comments
    
    def delete_comment(self):
        '''
        function that deletes a comment from database 
        '''
        db.session.delete(self)
        db.session.commit()
        
    def __repr__(self):
        '''
        function that helps in dec=bugging
        '''
        return f'Comment {self.body}'
            
            
            
            
            
            
            
            
            
        
        
    
    

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required
from flask_login import current_user 
 
class commentForm(FlaskForm):
    body = TextAreaField('Leave a comment:',validators=[Required()])
    submit = SubmitField('Post comment')
    

app/__init__.py
from flask import Flask
from config import Config
from flask_bootstrap import Bootstrap
from config import config_options
from flask_login import LoginManager
from flask_wtf.csrf import CSRFProtect
from flask_sqlalchemy import SQLAlchemy

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.loginview = 'auth.login'

bootstrap = Bootstrap()
csrf=CSRFProtect()
db = SQLAlchemy()

def create_app(config_name):
    
    app= Flask(__name__)

    #create app configs
    app.config.from_object(Config)
    app.config.from_object(config_options[config_name])
    app.config['SECRET_KEY']='d686414d5eeb7d38df7e8c385b2c2c47'
    
    #initializing
    bootstrap.init_app(app)
    csrf.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    
    #registering
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix = '/authenticate')
    
    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)

from . import views

app/main/views.py
from flask import render_template,redirect,url_for,request,abort
from . import main
from app import db 
from .. import db
from ..models import User,Admin,Parent,Comment
from .forms import commentForm
import datetime
from flask_login import login_required,current_user

@main.route('/')
def index():
    '''
    function that retuns the index
    '''
    title = 'school'
    return render_template('index.html',current_user=current_user)


@main.route('/admin')
@login_required
def admin():
    '''
    view root page function that returns thee index and its data
    '''
    title = 'admin portal'  
    
    return render_template('admin.html', title=title)

@main.route('/parent')
@login_required
def parent():
    '''
    view root page function that returns the index and its data
    '''
    title = 'parent portal'    
    
    return render_template('admin.html')

@main.route('/comments/', methods=['GET','POST'])
@login_required
def comments():
    
    form = commentForm()
    
    if form.validate_on_submit():
        body=form.body.data
        
        new_comment=Comment(body=body,posted_by=current_user.username,user_id=current_user.id)
        
        new_comment.save_comment()        
        return redirect(url_for('main.comments'))
    
    comments=Comment.get_comments()
    return render_template('comments.html',comments=comments,form=form)

@main.route('/photos')
def photos():
    
    return render_template('photos.html')

@main.route('/gallery')
def gallery():
    
    return render_template('gallery.html')

@main.route('/about')
def about():
    
    return render_template('about.html')

app/templates/about.html
{% block content %}  
{% include 'navbar.html' %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Playfair+Display&display=swap" rel="stylesheet">
<link rel="stylesheet" href="static/css/about.css">
<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div class="strt">
    <div class="overlay">
        <h1 class="about" id="about">WELCOME TO BRADFORD SCHOOL</h1>
        <img class="btn" href="#abt" src="http://2017.igem.org/wiki/images/7/7e/T--HZAU-China--arrow.gif
" width="200px"
            height="auto" alt="">
    </div>
</div>
<div class="about-us">
    <h2 class="htu">ABOUT US</h2>
    <p><span>Bradford School </span>is a small, private, for-profit[1] career college in Columbus,
        Ohio. It
        originally was founded in 1911 and moved to its current suburban campus location in 2003. It
        has
        on-ampus
        housing for students but more than half of students live in the Columbus area and commute.
    </p>
</div>
</div>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h1>BRAD<span>FORD</span></h1>
            </div>
            <div class="col-md-3">
                <ul>
                    <li><a href="#">Read our blog</a></li>
                    <li><a href="#">sign up</a></li>
                </ul>
            </div>
            <div class="col-md-3">
                <ul>
                    <li>Get Help</li>
                    <li>Read FAQS</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container" id="horizontal"></div>
    <div class="container" id="copyright">
        <div class="row">
            <div class="col-md-6">
                <p>Copyrights &copy; Bradford All rights reserved</p>
            </div>
            <div class="col-md-6">
                <i class="fa fa-twitter" style="font-size: 30px;padding: 12px"></i>
                <i class="fa fa-instagram" style="font-size: 30px;padding: 12px"></i>
                <i class="fa fa-facebook" style="font-size: 30px;padding: 12px"></i>
                <i class="fa fa-linkedin" style="font-size: 30px;padding: 12px"></i>
                <i class="fa fa-phone" style="font-size: 30px;padding: 12px"></i>
            </div>
        </div>
    </div>
</footer>
</div>
</div>
{% endblock content %}
<style>
    .strt {
        background-image: url('http://img.transcoder.opera.com/assets/v2/4177b52bba817b79aaa2e9bd9a4cd0e8');
        width: 1600px;
        background-repeat: no-repeat;
        height: 690px;
        background-size: cover;
        box-shadow: inset 0px 0px 0 2000px rgba(0, 0, 0, 0.5);
    }
    .about {
        color: white;
        text-align: center;
        font-size: 50px;
        font-weight: bolder;
        padding-top: 250px;
        margin-right: 300px;
        font-family: Georgia, 'Times New Roman', Times, serif;
    }
    img {
        margin-left: 500px;
        margin-top: 200px;
    }
    .htu {
        border-bottom: 2px solid black;
    }
    .about-us {
        width: 700px;
        padding: 100px;
    }
    footer {
        height: 70vh;
        background-color: #000000;
        margin-top: 30px;
        color: #fff;
        padding: 40px 0 0 60px;
    }
    footer span {
        color: rgb(67, 33, 219);
    }
    footer h1 {
        margin-bottom: 50px;
    }
    footer li {
        color: #fff;
        list-style: none;
    }
    footer a {
        color: #fff;
    }
    #horizontal {
        border-bottom: 1px solid #fff;
        padding-top: 50px;
    }
    #copyright {
        padding-top: 30px;
    }
    footer i {
        font-size: 30px;
    }
    .ml-auto,
    .mx-auto {
        margin-left: 35% !important;
    }
    *{
        overflow-x:hidden;
    }
</style>

app/templates/admin.html
{% include 'navbar.html' %} 
{% block content %}

<div class="container">
  <div class="categories">
    <div class="well well-lg">
      <div class="dates">
        <h1>SCHOOL DATES</h1><br>
        <p><strong> The school dates are as follows:</strong></p>
        <table >
            <tr>
             <th>School Holidays</th> 
             <th>Starts</th>
             <th>Finishes/Ends</th>
            </tr>
            <tr>
                <td>Term 1 Holidays</td>
                <td>6<sup>th</sup> January 2020 (opening)</td>
                <td>10<sup>th</sup> Apr 2020 (closing)</td>
            </tr>
            <tr>
               <td>Term 1 Half Term</td> 
               <td>17<sup>th</sup> Feb 2020</td>
               <td>21<sup>St</sup> Feb 2020</td>
            </tr>
            <tr>
                <td>Term 2 Holidays</td> 
                <td>4<sup>th</sup> May 2020 (opening)</td>
                <td>7<sup>th</sup> Aug 2020 (closing)</td>
             </tr>
            <tr>
                <td>Term 2 Half Term</td>
                <td>15<sup>th</sup> Jun 2020</td>
                <td>19<sup>th</sup> Jun 2020</td>
            </tr>
            <tr>
                <td>Term 3 Holidays</td> 
                <td>31<sup>St</sup> Aug 2020 (opening)</td>
                <td>30<sup>th</sup> Oct 2020 (closing)</td>
             </tr>
             <tr>
                <td>KCSE</td> 
                <td>6<sup>th</sup> Nov 2020 </td>
                <td>30<sup>th</sup> Nov 2020 </td>
             </tr>
        </table>
      </div>
    </div><br><br>
    <div class="well well-lg">
      <div class="dates">
        <h1>UPDATES</h1>
        <ul>
        <li><strong>The prize giving day is scheduled to be on 6<sup>th</sup> of March 2020. <br> Make a date and don't miss out. All the candidates are Invited and parents together <br> with friends are all welcome so we celebrate our students success together.</strong></li><br>
        <li><strong> Forms 1,2 & 3 have been given assignments kindly ensure the do the teachers work.</li><br>
        </ul>
        <h5>Form 3 Students are expected back with the following Setbooks:</h5>
        <ol>
            <li><em> The Pearl</em></li><br>
            <li><em>BLOSSOMS OF THE SAVANNAH</em></li><br>
            <li><em>A DOLL’S HOUSE</em></li><br>
            <li><em>Chozi la Heri</em></li><br>
            <li><em>Kigogo</em></li><br>
            <li><em> Tumbo Lisiloshiba na Hadithi Nyingine</em></li><br>
        </ol>
    </div>
    </div><br><br>
    <div class="well well-lg">
      <div class="dates">
        <h1>SCHOOL ACTIVITIES</h1>
        <p>All staff should take note of all school activities for conviniency.</p>
        <ul>
          <li>Science activities</li><br>
          <li>Craft Activities</li><br>
          <li>Games</li><br>
          <li>Trips</li><br>
        </ul>
      <p>  please ensure the parents are informed early about the activities so as to make payments as soon as possible.</p>
      </div>
    </div><br><br>
    <div class="well well-lg">
      <div class="dates">
        <h1>STAFF ACTIVITIES</h1>
        <p> The staff will be involved in the folloring activities:
          <p>GAMES</p>
          <ul>
            <li>Team Juggling</li><br>
            <li>Introduce Your Partner</li><br>
            <li>Beach Ball Questions</li><br>
            <li>Staff Bingo</li><br>
          </ul>
        </p>
      </div>
    </div>
  </div>
</div>

<a class="btn btn-primary" href="{{url_for('main.comments')}}">View comments</a>
{% endblock content %}
<style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }
    
    td, th {
      border: 1px solid #DDDDDD;
      padding: 8px;
    }
    
    tr:nth-child(even) {
      background-color: #AAAAAA;
    }
    h5{
        font-size: 30px;
    }
    h1,h5,p{
        text-align: center;
    }
    ul,ol{
        text-align: center;
        list-style-position: inside;
    }
    ul,li{
        justify-items: center;
    }
    .dates{
    font-size: 18px;
    }
 
   body{
   background-image: url("http://img.transcoder.opera.com/assets/v2/4177b52bba817b79aaa2e9bd9a4cd0e8");
   background-repeat: no-repeat;
   color: white;
   background-attachment:fixed ;
   background-size: cover;
    }
    </style>
    

app/templates/base.html
<meta name="viewport" content="width=device-width, initial-scale=1.0">

app/templates/comments.html
{% include 'navbar.html' %} {% import 'bootstrap/wtf.html' as wtf %}

{% block content%}
<div class="container">
    {{wtf.quick_form(form)}}
</div>

<div class="container">
  <div class="comments" style="text-align: center;">
   {% for comment in comments %}

    <h2 class="title" style="text-align: center;">{{comment.body}}</h2>
    <div class="body">
      <p class="posted">
        <small class="text-muted" style="padding-left: 100px;"
          >Posted on: {{comment.posted_on.strftime('%Y-%m-%d')}}</small
        >
        <small class="text-muted"
          ></small>
      </p>
      

    </div>
  </div>
</div>
{% endfor %}

{% endblock %}

app/templates/gallery.html
{% include 'navbar.html' %}
{% block content %}   

<div class="container">
  <div id="row">
      <div class="col-md-4">
          <img class="card-img-top" src="https://www.makinischool.ac.ke/wp-content/uploads/2018/11/sports-2.jpg" width="430px" height="350px" alt="Card image cap">
          <a>
            <div class="mask waves-effect waves-light rgba-white-slight"></div>
          </a>
          <!-- Social shares button -->
          <a class="activator mr-4"><i class="fas fa-share-alt"></i></a>
          <!-- Title -->
          <h4 class="card-title" id="left">Sports</h4>
          <p>sports activities reduce chronic muscular tension, strengthen lungs, <br> reduce blood sugar levels
             and regulate blood pressure. <br> Students involved
              in sports grow up as more energetic <br> individuals.</p>
          
          <button id="bt"><a href="#">View More</button></a> 
        </div>
        
          <!-- Card image -->
          <div class="col-md-4">
            <img class="card-img-top" src="https://www.standardmedia.co.ke/images/tuesday/kzgbqrit58wxc01j5d49c9e37a7f9.jpg" width="420px" height="350px" alt="Card image cap">
            <a>
              <div class="mask waves-effect waves-light rgba-white-slight"></div>
            </a>
      
            <!-- Title -->
            <h4 class="card-title" id="left">Drama</h4>
            <p>Drama is ideal for cross-curricular learning
               and is a valuable  tool <br> for use  in many subject
                areas. In particular, drama develops <br> literacy skills.
                 – supporting speaking and listening, <br> extending vocabulary</p>
            <button id="bt"><a href="#">View More</button></a>            
        
          </div>
        
            <!-- Card image -->
            <div class="col-md-4">
              <img class="card-img-top" src="http://www.kisc.sc.ke/wp-content/uploads/2017/12/kisc_cool-min-e1512634864704.jpg" alt="Card image cap" width="420px" height="350px">
              <a>
                <div class="mask waves-effect waves-light rgba-white-slight"></div>
              </a> 
              <!-- Social shares button -->
              <a class="activator mr-4"><i class="fas fa-share-alt"></i></a>
              <!-- Title -->
              <h4 class="card-title" id="left">School</h4>
              <p>The term curriculum refers to the lessons and academic content <br> 
                taught in a school or in a specific course or program. <br>
                 In dictionaries,
                  curriculum is often defined as the <br> courses offered  by a school, but it is rarely used <br> in such a general sense in schools.</p>
              
              <button id="bt"><a href="#">View More</a>
            </div> 
            </div>   
    
  </div>
  {% endblock content %}
  <style>
    #row{
      display: flex;
      justify-content: space-between;
    }
    #left{
     text-align: center;
     color:whitesmoke;
     text-decoration: underline;
     font-size: bold;
    }
    #bt{
      margin-left: 40%;
      font-size: 15px;
    }
    p{
      text-align: center;
      color:whitesmoke;
    }
    body{
      background-image: url("https://pikwizard.com/photos/7d792ebaa7177b9b5d79b4cc110e2c4a-m.jpg");
      background-repeat: no-repeat;
      background-size: cover;
      background-attachment: fixed;
    }
  </style>

app/templates/home.html
<meta name="viewport" content="width=device-width, initial-scale=1.0">

app/templates/navbar.html
    <link rel="stylesheet" href="static/css/index.css" type="text/css" />
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Navbar</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    />
    <link
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      rel="stylesheet"
      integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
      crossorigin="anonymous"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Noto+Sans+JP&display=swap"
      rel="stylesheet"
    />
  </head>

  <body>
    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <!-- Navbar brand -->

      <a
        class="fa fa-home nav-link btn btn-primary"
        style="font-weight: bolder;"
        href="/"
        >Home</a
      >

      <!-- Collapse button -->
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#basicExampleNav"
        aria-controls="basicExampleNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">
        <!-- Links -->
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a
              class="fa fa-group nav-link btn btn-primary"
              style="font-weight: bolder;"
              href="{{url_for('main.about')}}"
              >About
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item ml-5">
            <a
              class="fa fa-lock nav-link btn btn-primary"
              style="color: whitesmoke; font-weight: bolder;"
              href="{{url_for('main.admin')}}"
              >Admin</a
            >
          </li>
          <li class="nav-item ml-5">
            <a
              class="fa fa-user nav-link btn btn-primary"
              style="color: whitesmoke; font-weight: bolder;"
              href="{{url_for('main.parent')}}"
              >Parent</a
            >
          </li>
          <div class="dropdown">
              <li class="nav-item ml-5">
                  <a
                    class="fa fa-lock nav-link btn btn-primary"
                    style="color: whitesmoke; font-weight: bolder;"
                    href="{{url_for('main.gallery')}}"
                    >Gallery</a
                  >
                </li>
            <ul class="dropdown-menu">
              <li>
                <a style="font-family: 'Noto Sans JP', sans-serif;" href="#"
                  >SPORTS</a
                >
              </li>
              <li>
                <a style="font-family: 'Noto Sans JP', sans-serif;" href="#"
                  >DRAMA</a
                >
              </li>
              <li>
                <a style="font-family: 'Noto Sans JP', sans-serif;" href="#"
                  >SCHOOL</a
                >
              </li>
            </ul>
          </div>

          <li class="nav-item ml-5">
              <a
                class="fa fa-lock nav-link btn btn-primary"
                style="color: whitesmoke; font-weight: bolder;"
                href="{{url_for('main.photos')}}"
                >Photos</a
              >
            </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            
            <li class="dropdown">
              <a
                href="#"
                class="dropdown-toggle"
                data-toggle="dropdown"
                role="button"
                aria-haspopup="true"
                aria-expanded="false"
                ><span class="caret"></span
              ></a>
              <ul class="dropdown-menu">
                <li role="separator" class="divider"></li>
                <li><a href="{{url_for('auth.logout')}}" style="color: white;">Sign out</a></li>
              </ul>
            </li>
            
            <li><a href="{{url_for('auth.login')}}" style="color: white;">Login</a></li>
            <li><a href="{{url_for('auth.register')}}" style="color: white;">Register</a></li>
          </ul>
          

      </div>
      <!-- Collapsible content -->
    </nav>
    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>

app/templates/parent.html
{% include 'navbar.html' %}  {% block content %}

<div class="container">
  <div class="categories">
    <div class="well well-lg">
      <div class="dates">
        <h1>SCHOOL DATES</h1>
        <p>To all our parents, the school dates of the year are as follows:</p>
      </div>
    </div>

    <div class="well well-lg">
      <div class="dates">
        <h1>UPDATES</h1>
        <p>
          During this year, the school will be involved in various categories of
          school activities. Some various activities will be done in school
          while others will take place outside the school environment.We highlt
          encourage all parents to encourage their children to be involved in
          these outdoors activities.
        </p>
      </div>
    </div>

    <div class="well well-lg">
      <div class="dates">
        <h1>PERFOMANCE</h1>
        <p>
          Our school has been posting excellent perfomances for the past few
          years.The school is so proud and so grateful to all the parents for
          all your support.We like to give you some updates of our perfomances.
        </p>
      </div>
    </div>

    <div class="well well-lg">
      <div class="dates">
        <h1>PARENT STAFF HIGHLIGHTS</h1>
        <p>
          As a school,we would like to ensure all parents and staff work
          together to achieve the school objectives.Therefore,the school will be
          conducting meetings every term .Please take note of the dates.
        </p>
      </div>
    </div>

    <div class="well well-lg">
      <div class="dates">
        <h1></h1>
        <p></p>
      </div>
    </div>
  </div>
</div>


{% endblock content %}

<style>
  body {
    background-image: url("https://pikwizard.com/photos/7d792ebaa7177b9b5d79b4cc110e2c4a-m.jpg");
  }

  h1 {
    color: whitesmoke;
  }

  p {
    color: whitesmoke;
  }
</style>

app/templates/photos.html
{% block content %}   
  <div class="container-fluid">
    <div id="row">
    <div class="col-md-6">
    <h2>SPORTS</h2> 
  <img src="https://dar.braeburn.com/static/school/media/uploads/site-9/featured_images/.thumbnails/p8.jpg/p8-768x219.jpg" width="221px" height="200px" alt="">
  <img src="https://pbs.twimg.com/media/CyqGSQGWQAAs-uW.jpg" width="221px" height="200px" alt="">
  <img src="http://ragahouse.com/content/photos/changez-1.jpg" width="221px" height="200px" alt="">
  <img src="http://www.dsnairobi.de/files/20181101_093931_001_02_lr450_1.jpg" width="221px" height="200" alt="">
  <img src="https://3dwnh01icn0h133s00sokwo1-wpengine.netdna-ssl.com/wp-content/uploads/2017/04/Basketball.jpeg" width="221px" height="200px" alt="">
  <img src="https://www.kenyabuzz.com/lifestyle/wp-content/uploads/2018/08/kids-800x480.jpg" width="210px" height="200px" alt="">
</div>


<div>
  <h2>DRAMA</h2>
  <img src="https://www.nation.co.ke/image/view/-/4327862/highRes/1899578/-/yp4e79/-/drama-pic.jpg" width="221px" height="200px" alt="">
  <img src="https://www.ocf.berkeley.edu/~culturalanalysis/volume15_2/img/kiiru_1.jpg" width="221px" height="200px" alt="">
  <img src="https://i0.wp.com/rockfields.ac.ke/wp-content/uploads/2018/07/DSCN1692.jpg" width="221px" height="200px" alt="">
  <img src="https://www.jonathangloag.ac.ke/images/drama/Drama4.JPG" width="221px" height="200px" alt="">
  <img src="http://2.bp.blogspot.com/-LHpIDGe5QU4/VjtW6fFWuQI/AAAAAAAAAoc/K_sfdGnPNY0/s1600/credai4.jpg" width="221px" height="200" alt="">
  <img src="https://images-na.ssl-images-amazon.com/images/I/91ZN%2BkHiKxL._SX466_PIcountsize-3,TopRight,0,0_SX466SY386SH20_.jpg" width="200px" height="200px" alt="">

</div>
<div>
<h2>SCHOOL</h2>
  <img src="https://constructingkids.files.wordpress.com/2012/12/crawl-on-the-walls-st-joseph_s-primary-school-library-in-melbourne.png" width="221px" height="200px" alt="">
  <img src="http://dkarchitects.in/wp-content/uploads/2019/01/ARIC0278.jpg" width="221px" height="200px" alt="">
  <img src="https://i.pinimg.com/originals/ea/24/2b/ea242bd0cbb89dc5f8ed4c34a0562a09.jpg" width="221px" height="200px" alt="">
  <img src="https://industrialtalks.files.wordpress.com/2014/01/2.jpg" width="221px" height="200px" alt="">
  <img src="https://s8z7g7z7.stackpathcdn.com/sites/default/files/styles/project/public/projects/inclusive-playground-shaparral-elementary-nm.jpg?" width="221px" height="200px" alt="">
  <img src="https://assets.change.org/photos/5/vu/zo/uXVuZoSTGfEhBgM-800x450-noPad.jpg?" width="200px" height="200px" alt="">

</div>
</div>
</div>

{% endblock content %}

<style>
body{
  background-image: url("https://pikwizard.com/photos/7d792ebaa7177b9b5d79b4cc110e2c4a-m.jpg");
  background-repeat: no-repeat;
  background-size: cover;
  background-attachment: fixed;
}
  h2{
    text-align: center;
    color: whitesmoke;
    text-decoration: underline;
  }
</style>